// AUTO-GENERATED by sns-auto-poster — do not edit manually.
// Source contract: docs/ctx/aurum-blog-feed.md
// 임시: 사용자 mockup 검수용으로 직접 채움 (2026-05-16). sns-auto-poster export 첫 실행 시 덮어쓰임.

export interface BlogPost {
  id: string;
  title: string;
  url: string;
  category: '기업 복지 케어' | '행사 케어' | '웰니스·힐링 프로그램';
  date: string;               // 블로그 발행일 YYYY-MM-DD
  eventDate: string | null;   // 실제 행사일 YYYY-MM or YYYY-MM-DD (null 가능)
  thumbnail: string;
}

export const LATEST_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post_53',
    title: '임직원 복지 마사지 | 태건 BF 복지시설 피지컬 케어',
    url: 'https://blog.naver.com/aurumwellness/224281385555',
    category: '기업 복지 케어',
    date: '2026-05-11',
    eventDate: '2020-05',
    thumbnail: '/blog-thumbs/post-53.png',
  },
  {
    id: 'post_52',
    title: '임직원 복지 마사지 | CEO SUITE 파르나스점 입주민 피지컬 케어',
    url: 'https://blog.naver.com/aurumwellness/224278545926',
    category: '기업 복지 케어',
    date: '2026-05-08',
    eventDate: '2020-02',
    thumbnail: '/blog-thumbs/post-52.png',
  },
  {
    id: 'post_50',
    title: '기업행사 핸드마사지 이벤트 행사 | 패스트파이브 라이프온투게더 & 롯데백화점 영등포점 추석 이벤트',
    url: 'https://blog.naver.com/aurumwellness/224275929800',
    category: '행사 케어',
    date: '2026-05-05',
    eventDate: '2020-01',
    thumbnail: '/blog-thumbs/post-50.png',
  },
];

/**
 * eventDate (YYYY-MM 또는 YYYY-MM-DD)를 한글 표기로 포맷.
 * "2020-05" → "2020년 5월"
 * "2020-05-06" → "2020년 5월 6일"
 * null/undefined → null
 */
export function formatEventDate(eventDate: string | null | undefined): string | null {
  if (!eventDate) return null;
  const parts = eventDate.split('-');
  const year = parts[0];
  const month = parts[1] ? parseInt(parts[1], 10) : null;
  const day = parts[2] ? parseInt(parts[2], 10) : null;
  if (!year || !month) return null;
  return day ? `${year}년 ${month}월 ${day}일` : `${year}년 ${month}월`;
}

export const CATEGORY_COLORS: Record<BlogPost['category'], string> = {
  '기업 복지 케어': '#D4B896',
  '행사 케어': '#7AAFCF',
  '웰니스·힐링 프로그램': '#8EBE7E',
};

export const NAVER_BLOG_URL = 'https://blog.naver.com/aurumwellness';
